In [2]:
import numpy as np

### #1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### #2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
M = np.zeros((3, 3), dtype=int)
print(M)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### #3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
M = np.random.randint(1, 11, size=(5, 5))
print(M)

[[ 2  5  4  6  6]
 [ 2  5  7  8  7]
 [ 8  3  7 10  1]
 [ 4  9  6  5  9]
 [ 9  6  8  2  4]]


### #4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [7]:
M = np.random.random((4, 4))
print(M)

[[0.32628198 0.41872203 0.10410181 0.21969903]
 [0.44995852 0.61245025 0.43450289 0.99206629]
 [0.75750726 0.07682535 0.71188408 0.85171519]
 [0.10207923 0.78359159 0.59973673 0.24429206]]


### #5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [8]:
a = np.random.randint(1, 11, size=(5,))
b = np.random.randint(1, 11, size=(5,))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[ 3 10  6  8  4]
[ 4  4  4 10  5]
[ 7 14 10 18  9]
[-1  6  2 -2 -1]
[12 40 24 80 20]


### #6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [9]:
a = np.random.randint(1, 11, size=(7))
b = np.random.randint(1, 11, size=(7))
print(a)
print(b)
print(np.dot(a, b))

[ 5  2  3 10  9  4  6]
[10  2  8  6  5  6  9]
261


### #7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [11]:
M = np.random.randint(1, 11, size=(2, 2))
N = np.random.randint(1, 11, size=(2, 3))
print(M)
print(N)
print(np.dot(M, N))

[[2 6]
 [8 3]]
[[3 6 7]
 [7 4 5]]
[[48 36 44]
 [45 60 71]]


### #8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [15]:
M = np.random.randint(1, 11, size=(3, 3))
print(M)
print(np.linalg.inv(M))

[[10  5  6]
 [ 1  9  2]
 [ 3  8  6]]
[[ 0.14285714  0.06766917 -0.16541353]
 [ 0.          0.15789474 -0.05263158]
 [-0.07142857 -0.2443609   0.31954887]]


### #9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [18]:
M = np.random.random((4, 4))
print(M)
print(M.T)

[[0.21261568 0.5665961  0.45043236 0.81160423]
 [0.1943207  0.88017669 0.19175593 0.94255193]
 [0.57936718 0.59608192 0.00248547 0.88007764]
 [0.7222632  0.80223577 0.50739303 0.10586923]]
[[0.21261568 0.1943207  0.57936718 0.7222632 ]
 [0.5665961  0.88017669 0.59608192 0.80223577]
 [0.45043236 0.19175593 0.00248547 0.50739303]
 [0.81160423 0.94255193 0.88007764 0.10586923]]


### #10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [19]:
M = np.random.randint(1, 11, size=(3, 4))
a = np.random.randint(1, 11, size=(4))
print(M)
print(a)
print (np.dot(M, a))

[[3 6 1 9]
 [2 1 4 4]
 [1 5 1 3]]
[9 8 1 5]
[121  50  65]


### #11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [22]:
M = np.random.random(size=(2, 3))
a = np.random.random(size=(3))
print(M)
print(a)
print (np.dot(M, a))

[[0.03113731 0.72685408 0.30371223]
 [0.85485252 0.63866297 0.01454507]]
[0.12983285 0.42854262 0.95621907]
[0.60594603 0.39859052]


### #12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [23]:
M = np.random.randint(1, 11, size=(2, 2))
N = np.random.randint(1, 11, size=(2, 2))
print(M)
print(N)
print(M*N)

[[ 2 10]
 [ 5  1]]
[[3 2]
 [6 9]]
[[ 6 20]
 [30  9]]


### #13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [24]:
M = np.random.randint(1, 11, size=(2, 2))
N = np.random.randint(1, 11, size=(2, 2))
print(M)
print(N)
print(np.dot(M, N))

[[5 1]
 [6 3]]
[[ 5 10]
 [ 9  1]]
[[34 51]
 [57 63]]


### #14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [25]:
M = np.random.randint(1, 101, size=(5, 5))
print(M)
print(M.sum())

[[92 26  7 66 58]
 [39 63 64 78 70]
 [90 91 77  3 11]
 [91 90 35 85 23]
 [50 85 59 13 48]]
1414


### #15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [27]:
M = np.random.randint(1, 11, size=(4, 4))
N = np.random.randint(1, 11, size=(4, 4))
print(M)
print(N)
print(M-N)
print(N-M)

[[ 2 10  9 10]
 [ 6  6  9  9]
 [ 7  1  4  2]
 [ 6  9  7  8]]
[[ 4  8  1 10]
 [ 1  6  2  9]
 [ 2  3  4  4]
 [ 6  6  8  2]]
[[-2  2  8  0]
 [ 5  0  7  0]
 [ 5 -2  0 -2]
 [ 0  3 -1  6]]
[[ 2 -2 -8  0]
 [-5  0 -7  0]
 [-5  2  0  2]
 [ 0 -3  1 -6]]


### #16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [40]:
M = np.random.random((3, 3))
print(M)
v = M.sum(axis=1).reshape(3, 1)
print(v)

[[0.03418056 0.97685505 0.47175348]
 [0.11951024 0.2696351  0.92132472]
 [0.02421034 0.0831528  0.29505114]]
[[1.4827891 ]
 [1.31047006]
 [0.40241429]]


### #17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [41]:
M = np.random.randint(1, 11, size=(3, 4))
N = np.square(M)
print(M)
print(N)

[[3 2 9 8]
 [3 5 7 9]
 [8 4 6 3]]
[[ 9  4 81 64]
 [ 9 25 49 81]
 [64 16 36  9]]


### #18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [43]:
a = np.random.randint(1, 51, size=(4))
b = np.sqrt(a)
print(a)
print(b)

[33 42 11 32]
[5.74456265 6.4807407  3.31662479 5.65685425]
